### ISSUE TITLE
Query regarding English speech encoder model used for SubSONAR

### ISSUE THREAD

**Issue by miagrbr-MC** [hlt-mt/subsonar#4]
Good day, 

Thank you so much for making SubSONAR available, it has been immensely useful in my research thus far :) 

I have a small query regarding the English speech encoder model that is used by SubSONAR. From my understanding, SubSONAR uses the speech encoder models from the SONAR repository, however when visiting the link (https://github.com/facebookresearch/SONAR/blob/main/README.md#supported-languages-and-download-links ) English is notably not listed as one of the available speech encoders. 

I had a look at the models offered on the SONAR Huggingface page, and while there is no English speech encoder offered in the root folder i.e. `main` (https://huggingface.co/facebook/SONAR/tree/main) within the `fairseq2_native` folder there is a `sonar_speech_encoder_eng.pt` model listed (https://huggingface.co/facebook/SONAR/tree/main/fairseq2_native) which is what I had assumed is what SubSONAR uses. 

Upon closer inspection however, when I run SubSONAR, I notice that a speech encoder called `spenc.eng.pt` is downloaded to `.cache/fairseq2/assets/5f4057a558a791ac037a743c` which does not look to correspond to the aforementioned `sonar_speech_encoder_eng.pt` model (https://huggingface.co/facebook/SONAR/tree/main/fairseq2_native). 

I was just hoping for some clarity regarding where the English speech encoder model comes from, and why the English speech encoder offered by the SONAR Huggingface repository is not used. 

Thank you so much for your time and consideration :) 

Kind regards,
Mia

**Comment by mgaido91** [comment]
Hi Mia,

thanks for your question.
I did not notice that `eng` is not listed in the audio encoders in SONAR, but it is mentioned in their examples (e.g. see https://github.com/facebookresearch/SONAR?tab=readme-ov-file#speech-to-text-translation-with-sonar).

We are using sonar's `SpeechToEmbeddingModelPipeline` (see https://github.com/hlt-mt/subsonar/blob/main/src/subsonar/sonar_metric.py#L108C30-L108C60) to get the audio encoder, which uses SONAR's `ModelLoader` taken from `fairseq2` (see https://github.com/facebookresearch/SONAR/blob/main/sonar/models/sonar_speech/loader.py#L88). I do not know why they use this instead of the Huggingface version, my best guess is that the huggingface version is a porting of the fairseq2 models, so they prefer to go for the native fairseq2 models.

Hope this helps.
Marco

**Comment by miagrbr-MC** [comment]
Hi @mgaido91 thank you so much for your detailed response! It helps a lot to clear this up :)
